exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME

gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-polyglot

title: Ruby on Rails
description: A web-application framework that includes everything needed to create database-backed web applications according to the Model-View-Controller (MVC) pattern.
twitter:
  username: rails

# polyglot-specific settings
languages: ["en", "ru", "tr"]
default_lang: "en"
exclude_from_localization: ["materials", "images"]
parallel_localization: true
