exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

title: Azzen Abidi
description: A marketer with a hacker mindset on a journey to make a dent in the universe
twitter:
  username: azzenabidi
defaults:
  - scope:
      path: ""
    values:
      image: 
